spring:
  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:postgresql://localhost:5432/security
    username: postgres
    password: password
logging:
  level:
    org:
      springframework:
        security: debug
